export const Beer_data = [
  {
    "idDrink": "15423",
    "strDrink": "110 in the shade",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Beer Glass",
    "strInstructions": "Drop shooter in glass. Fill with beer",
    "strInstructionsES": null,
    "strInstructionsDE": "Shooter tröpfchenweise in ein Glas geben. Mit Bier füllen.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xxyywq1454511117.jpg",
    "strIngredient1": "Lager",
    "strIngredient2": "Tequila",
    "strIngredient3": null,
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "16 oz ",
    "strMeasure2": "1.5 oz ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-02-03 14:51:57"
  },
  {
    "idDrink": "13282",
      "strDrink": "Black & Tan",
      "strDrinkAlternate": null,
      "strDrinkES": null,
      "strDrinkDE": null,
      "strDrinkFR": null,
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Beer",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Pint glass",
      "strInstructions": "Fill pint glass half full with Bass. Next pour Guiness over a spoon slowly until glass is full. If done correctly the Guiness will stay on top and the Bass on bottom hence the name Black & Tan.",
      "strInstructionsES": null,
      "strInstructionsDE": "Füllen Sie das Pintglas halb voll mit Bass. Als nächstes Guiness langsam über einen Löffel gießen, bis das Glas voll ist. Wenn richtig gemacht, bleibt der Guiness oben und der Bass unten, daher der Name Black & Tan.",
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rwpswp1454511017.jpg",
      "strIngredient1": "Ale",
      "strIngredient2": "Guinness stout",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 part Bass pale ",
      "strMeasure2": "1 part ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-02-03 14:50:17"
  },
  {
    "idDrink": "16403",
    "strDrink": "Black and Brown",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Beer pilsner",
    "strInstructions": "CAREFULLY to avoid explosive head formation: Pour Beer glass half full of favorite rootbeer and top off with Guinness.",
    "strInstructionsES": null,
    "strInstructionsDE": "Sorgfältig vorgehen, um eine explosive Kopfverformung zu vermeiden: Gießen Sie ein Bierglas halb voll mit beliebten Rootbeeren und verfeinern Sie es mit Guinness.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wwuvxv1472668899.jpg",
    "strIngredient1": "Guinness stout",
    "strIngredient2": "Root beer",
    "strIngredient3": null,
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1/2 ",
    "strMeasure2": "1/2 ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-08-31 19:41:39"
  },
  {
    "idDrink": "17035",
      "strDrink": "Buccaneer",
      "strDrinkAlternate": null,
      "strDrinkES": null,
      "strDrinkDE": null,
      "strDrinkFR": null,
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Beer",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Beer pilsner",
      "strInstructions": "Pour the corona into an 18oz beer glass pour the bacardi limon into the beer stir very gently",
      "strInstructionsES": null,
      "strInstructionsDE": "Gießen Sie die Korona in ein Bierglas und gießen Sie die Bacardi-Limone in das Bier. Rühren Sie sehr sanft.",
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/upvtyt1441249023.jpg",
      "strIngredient1": "Corona",
      "strIngredient2": "Bacardi Limon",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 ",
      "strMeasure2": "1 shot ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-03 03:57:03"
  },
  {
    "idDrink": "16047",
      "strDrink": "Campari Beer",
      "strDrinkAlternate": null,
      "strDrinkES": null,
      "strDrinkDE": null,
      "strDrinkFR": null,
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Beer",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Beer mug",
      "strInstructions": "Use a 15 oz glass. Add Campari first. Fill with beer.",
      "strInstructionsES": null,
      "strInstructionsDE": "Verwenden Sie ein 15 oz Glas. Zuerst Campari hinzufügen. Mit Bier auffüllen.",
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xsqrup1441249130.jpg",
      "strIngredient1": "Lager",
      "strIngredient2": "Campari",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 bottle ",
      "strMeasure2": "1 1/2 cl ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-03 03:58:50"
  },
  {
    "idDrink": "17065",
    "strDrink": "Caribbean Boilermaker",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Beer pilsner",
    "strInstructions": "Pour the Corona into an 18oz beer glass pour the rum into the beer.",
    "strInstructionsES": null,
    "strInstructionsDE": "Gießen Sie die Corona in ein Bierglas und gießen Sie den Rum in das Bier.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/svsxsv1454511666.jpg",
    "strIngredient1": "Corona",
    "strIngredient2": "Light rum",
    "strIngredient3": null,
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1 bottle ",
    "strMeasure2": "1 shot ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-02-03 15:01:06"
  },
  {
    "idDrink": "13128",
    "strDrink": "Diesel",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Pint glass",
    "strInstructions": "Pour the lager first then add the blackcurrant cordial. Top up with the cider. The colour sholud be very dark approaching the colour of Guiness.",
    "strInstructionsES": null,
    "strInstructionsDE": "Zuerst das Lagerbier gießen und dann die schwarze Johannisbeere hinzufügen. Mit dem Apfelmost auffüllen. Die Farbe sollte sehr dunkel sein und sich der Farbe von Guiness nähern.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/sxrrqq1454512852.jpg",
    "strIngredient1": "Lager",
    "strIngredient2": "Cider",
    "strIngredient3": "Blackcurrant cordial",
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1/2 pint ",
    "strMeasure2": "1/2 pint ",
    "strMeasure3": "1 dash ",
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-02-03 15:20:52"
  },
  {
    "idDrink": "13497",
    "strDrink": "Green Goblin",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Pint glass",
    "strInstructions": "Cider First, Lager then Curacao",
    "strInstructionsES": null,
    "strInstructionsDE": "Zuerst Apfelwein, dann Lager und Curacao.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qxprxr1454511520.jpg",
    "strIngredient1": "Cider",
    "strIngredient2": "Lager",
    "strIngredient3": "Blue Curacao",
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1/2 pint hard ",
    "strMeasure2": "1/2 pint ",
    "strMeasure3": "1 shot ",
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-02-03 14:58:40"
  },
  {
    "idDrink": "17015",
    "strDrink": "Irish Russian",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Highball glass",
    "strInstructions": "Add the ingredients in the order listed in the recipe. Care must be taken when adding the Guinness to prevent an excess of foam. Do Not add ice.",
    "strInstructionsES": null,
    "strInstructionsDE": "Fügen Sie die Zutaten gemäß der im Rezept angegebenen Reihenfolge hinzu. Beim Hinzufügen des Guinness ist Vorsicht geboten, um einen Schaumüberschuss zu vermeiden. Füge kein Eis hinzu.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/swqurw1454512730.jpg",
    "strIngredient1": "Vodka",
    "strIngredient2": "Kahlua",
    "strIngredient3": "Coca-Cola",
    "strIngredient4": "Guinness stout",
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1 shot ",
    "strMeasure2": "1 shot ",
    "strMeasure3": "1 dash ",
    "strMeasure4": "Fill with ",
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-02-03 15:18:50"
  },
  {
    "idDrink": "15086",
    "strDrink": "Limona Corona",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Beer Glass",
    "strInstructions": "Open the Corona. Fill the empty space in the neck in the bottle with the rum. The bottle should be filled to the top. Plug the bottle with your thumb or the palm of your hand. Turn the bottle upside-down so the rum and beer mix. Turn the bottle rightside-up, unplug, and drink.",
    "strInstructionsES": null,
    "strInstructionsDE": "Öffne die Corona. Füllen Sie den leeren Platz im Hals in der Flasche mit dem Rum. Die Flasche sollte bis zum Anschlag gefüllt werden. Die Flasche mit dem Daumen oder der Handfläche verschließen. Drehen Sie die Flasche auf den Kopf, damit sich Rum und Bier vermischen. Drehen Sie die Flasche nach oben, ziehen Sie den Daumen heraus und trinken Sie.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wwqrsw1441248662.jpg",
    "strIngredient1": "Corona",
    "strIngredient2": "Bacardi Limon",
    "strIngredient3": null,
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1 bottle ",
    "strMeasure2": "1 oz ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2015-09-03 03:51:02"
  },
  {
   
    "idDrink": "14378",
    "strDrink": "Lunch Box",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Pint glass",
    "strInstructions": "Fill a pint glass almost full with beer. Then fill the rest with orange juice (careful not to fill it to the top). Then take the shot of Amaretto and drop it in.",
    "strInstructionsES": null,
    "strInstructionsDE": "Füllen Sie ein Pintglas fast voll mit Bier. Dann den Rest mit Orangensaft füllen (darauf achten, ihn nicht nach oben zu füllen). Dann nimm den Schuss Amaretto und lass ihn rein.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qywpvt1454512546.jpg",
    "strIngredient1": "Beer",
    "strIngredient2": "Amaretto",
    "strIngredient3": "Orange juice",
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "3/4 bottle ",
    "strMeasure2": "1 shot ",
    "strMeasure3": "1 oz ",
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-02-03 15:15:46"
  },
  {
    "idDrink": "13389",
      "strDrink": "Snake Bite (UK)",
      "strDrinkAlternate": null,
      "strDrinkES": null,
      "strDrinkDE": null,
      "strDrinkFR": null,
      "strDrinkZH-HANS": null,
      "strDrinkZH-HANT": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Beer",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Pint glass",
      "strInstructions": "Pour ingredients into a pint glass. Drink. Fall over.",
      "strInstructionsES": null,
      "strInstructionsDE": "Zutaten in ein Glas geben. Trink. Fall um.",
      "strInstructionsFR": null,
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xuwpyu1441248734.jpg",
      "strIngredient1": "Lager",
      "strIngredient2": "Cider",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1/2 pint ",
      "strMeasure2": "1/2 pint sweet or dry ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-03 03:52:14"
  },
  {
    "idDrink": "15789",
    "strDrink": "Snakebite and Black",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Beer",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Pint glass",
    "strInstructions": "Put blackcurrant squash in first up to about 1cm in glass. Then add the larger and cider one after another.",
    "strInstructionsES": null,
    "strInstructionsDE": "Zuerst den schwarzen Johannisbeer-Kürbis bis zu ca. 1 cm in ein Glas geben. Dann das Lagerbier und den Apfelwein nacheinander hinzufügen.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rssvwv1441248863.jpg",
    "strIngredient1": "Lager",
    "strIngredient2": "Cider",
    "strIngredient3": "Blackcurrant squash",
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1/2 pint ",
    "strMeasure2": "1/2 pint ",
    "strMeasure3": "A little bit of ",
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2015-09-03 03:54:23"
  },
];
