export const cock_data = [
  {
    idDrink: "14029",
    strDrink: "'57 Chevy with a White License Plate",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "1. Fill a rocks glass with ice 2.add white creme de cacao and vodka 3.stir",
    strInstructionsES: null,
    strInstructionsDE:
      "1. Füllen Sie ein Rocks Glas mit Eis 2. Geben Sie weiße Creme de Kakao und Wodka hinzu. 3. Umrühren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/qyyvtu1468878544.jpg",
    strIngredient1: "Creme de Cacao",
    strIngredient2: "Vodka",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz white ",
    strMeasure2: "1 oz ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-07-18 22:49:04",
  },
  {
    idDrink: "15346",
    strDrink: "155 Belmont",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "White wine glass",
    strInstructions:
      "Blend with ice. Serve in a wine glass. Garnish with carrot.",
    strInstructionsES: null,
    strInstructionsDE:
      "Mit Eis vermischen. In einem Weinglas servieren. Mit Karotte garnieren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg",
    strIngredient1: "Dark rum",
    strIngredient2: "Light rum",
    strIngredient3: "Vodka",
    strIngredient4: "Orange juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "2 shots ",
    strMeasure3: "1 shot ",
    strMeasure4: "1 shot ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-10-05 12:36:28",
  },
  {
    idDrink: "178318",
    strDrink: "747 Drink",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Fill a Collins glass with ice.\r\nPour in vodka, lime cordial, and cranberry juice.\r\nFill up with Sprite.\r\nGarnish with a Lime wheel or some cranberries",
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/i9suxb1582474926.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Roses sweetened lime juice",
    strIngredient3: "Cranberry Juice",
    strIngredient4: "Sprite",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz",
    strMeasure2: "1 oz",
    strMeasure3: "1 oz",
    strMeasure4: "Top",
    strMeasure5: "",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "Yes",
    dateModified: null,
  },
  {
    idDrink: "16108",
    strDrink: "9 1/2 Weeks",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Combine all ingredients in glass mixer. Chill and strain into Cocktail glass. Garnish with sliced strawberry.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in einem Glasmischer vermengen. Abkühlen lassen und in das Cocktailglas abseihen. Mit Erdbeerscheiben garnieren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg",
    strIngredient1: "Absolut Citron",
    strIngredient2: "Orange Curacao",
    strIngredient3: "Strawberry liqueur",
    strIngredient4: "Orange juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1 splash ",
    strMeasure4: "1 oz ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:48:22",
  },
  {
    idDrink: "16943",
    strDrink: "A Gilligan's Island",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions: "Shaken, not stirred!",
    strInstructionsES: null,
    strInstructionsDE: "Geschüttelt, nicht gerührt!",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/wysqut1461867176.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Peach schnapps",
    strIngredient3: "Orange juice",
    strIngredient4: "Cranberry juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "3 oz ",
    strMeasure4: "3 oz ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-04-28 19:12:56",
  },
  {
    idDrink: "17005",
    strDrink: "A True Amaretto Sour",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Old-fashioned glass",
    strInstructions:
      'Rub the rim of an old fashioned glass with lemon, and dip repeatedly into granulated sugar until it has a good "frosted" rim. Shake a jigger of Amaretto with the juice of 1/2 a lemon. Strain into glass and add ice. Garnish with a Marachino Cherry.',
    strInstructionsES: null,
    strInstructionsDE:
      'Reiben Sie den Rand eines old fashioned Glases mit Zitrone ein und tauchen Sie es wiederholt in Kristallzucker, bis es einen guten "gefrosteten" Rand hat. Einen Jigger Amaretto mit dem Saft von 1/2 Zitrone schütteln. In ein Glas abseihen und Eis hinzufügen. Mit einer Marachinokirsche garnieren.',
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/rptuxy1472669372.jpg",
    strIngredient1: "Amaretto",
    strIngredient2: "Lemon",
    strIngredient3: "Ice",
    strIngredient4: "Maraschino cherry",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 jigger ",
    strMeasure2: "Juice of 1/2 ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:49:32",
  },
  {
    idDrink: "14560",
    strDrink: "A.D.M. (After Dinner Mint)",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Irish coffee cup",
    strInstructions: "shake vigorously",
    strInstructionsES: null,
    strInstructionsDE: "kräftig schütteln",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ruxuvp1472669600.jpg",
    strIngredient1: "White Creme de Menthe",
    strIngredient2: "Southern Comfort",
    strIngredient3: "Vodka",
    strIngredient4: "Hot chocolate",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1/2 oz ",
    strMeasure2: "3/4 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: "Fill with ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:53:20",
  },
  {
    idDrink: "17222",
    strDrink: "A1",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Grand Marnier",
    strIngredient3: "Lemon Juice",
    strIngredient4: "Grenadine",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 3/4 shot ",
    strMeasure2: "1 Shot ",
    strMeasure3: "1/4 Shot",
    strMeasure4: "1/8 Shot",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 21:42:09",
  },
  {
    idDrink: "17223",
    strDrink: "Abbey Martini",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Put all ingredients into a shaker and mix, then strain contents into a chilled cocktail glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in einen Shaker geben und mischen, dann den Inhalt in ein gekühltes Cocktailglas abseihen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/2mcozt1504817403.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Sweet Vermouth",
    strIngredient3: "Orange Juice",
    strIngredient4: "Angostura Bitters",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 shots ",
    strMeasure2: "1 shot ",
    strMeasure3: "1 shot ",
    strMeasure4: "3 dashes ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 21:50:03",
  },
  {
    idDrink: "14107",
    strDrink: "Absolut Summertime",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions:
      "Add all ingredients except lemon to shaker filled with ice. Cover and shake vigorously. Strain contents into ice filled collins glass. Garnish with lemon.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten außer Zitrone in den mit Eis gefüllten Shaker geben. Abdecken und kräftig schütteln. Inhalt in eisgefülltes Collins-Glas abseihen. Mit Zitrone garnieren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/trpxxs1472669662.jpg",
    strIngredient1: "Absolut Citron",
    strIngredient2: "Sweet and sour",
    strIngredient3: "Sprite",
    strIngredient4: "Soda water",
    strIngredient5: "Lemon",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "3/4 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: "3 oz ",
    strMeasure5: "1 slice ",
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:54:22",
  },
  {
    idDrink: "17224",
    strDrink: "Absolutely Fabulous",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Champagne flute",
    strInstructions:
      "Mix the Vodka and Cranberry juice together in a shaker and strain into a glass. Top up with Champagne.",
    strInstructionsES: null,
    strInstructionsDE:
      "Den Wodka- und Preiselbeersaft in einem Shaker vermischen und in ein Glas abseihen. Mit Champagner auffüllen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/abcpwr1504817734.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Cranberry Juice",
    strIngredient3: "Champagne",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "2 shots ",
    strMeasure3: "Top up with",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 21:55:34",
  },
  {
    idDrink: "16134",
    strDrink: "Absolutly Screwed Up",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions:
      "Shake it up it tasts better that way, but you can stir it if you want. 6 of those and you will be wasted for the rest of the night.",
    strInstructionsES: null,
    strInstructionsDE:
      "Schütteln Sie, schmeckt es besser, aber Sie können es auch rühren, wenn Sie wollen. 6 davon und du wirst für den Rest der Nacht erledigt sein.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yvxrwv1472669728.jpg",
    strIngredient1: "Absolut Citron",
    strIngredient2: "Orange juice",
    strIngredient3: "Triple sec",
    strIngredient4: "Ginger ale",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "1 shot ",
    strMeasure3: "1 shot ",
    strMeasure4: "Fill to top ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:55:28",
  },
  {
    idDrink: "17225",
    strDrink: "Ace",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Martini Glass",
    strInstructions:
      "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Grenadine",
    strIngredient3: "Heavy cream",
    strIngredient4: "Milk",
    strIngredient5: "Egg White",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 shots ",
    strMeasure2: "1/2 shot ",
    strMeasure3: "1/2 shot ",
    strMeasure4: "1/2 shot",
    strMeasure5: "1/2 Fresh",
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 22:05:06",
  },
  {
    idDrink: "17226",
    strDrink: "Adam & Eve",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Shake together all the ingredients and strain into a cold glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten vermengen und in ein kaltes Glas abseihen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Cognac",
    strIngredient3: "Creme de Cassis",
    strIngredient4: "Fresh Lemon Juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "1 shot ",
    strMeasure3: "1 shot ",
    strMeasure4: "1/8 shot ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 22:17:58",
  },
  {
    idDrink: "17227",
    strDrink: "Addington",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Mix both the vermouth's in a shaker and strain into a cold glass. Top up with a squirt of Soda Water. ",
    strInstructionsES: null,
    strInstructionsDE:
      "Mischen Sie beide Wermutarten in einem Shaker und sieben Sie sie in ein kaltes Glas. Mit einem Spritzer Sodawasser auffüllen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ib0b7g1504818925.jpg",
    strIngredient1: "Sweet Vermouth",
    strIngredient2: "Dry Vermouth",
    strIngredient3: "Soda Water",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 shots ",
    strMeasure2: "1 shot ",
    strMeasure3: "Top up with\r\n",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 22:15:25",
  },
  {
    idDrink: "17228",
    strDrink: "Addison",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Martini Glass",
    strInstructions:
      "Shake together all the ingredients and strain into a cold glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten vermengen und in ein kaltes Glas abseihen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Vermouth",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 shot ",
    strMeasure2: "1 1/2 shot ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 22:38:20",
  },
  {
    idDrink: "14272",
    strDrink: "Addison Special",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Old-fashioned glass",
    strInstructions:
      "Combine ingredients in the order listed into a shaker. Fill half full with ice and shake well. Strain into glass with ice and garnish with a cherry and orange wedge.",
    strInstructionsES: null,
    strInstructionsDE:
      "Mische die Zutaten in der angegebenen Reihenfolge in einem Shaker. Halb voll mit Eis füllen und gut schütteln. In ein Glas mit Eis abseihen und mit einem Kirsch- und Orangenkeil garnieren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/4vo5651493068493.jpg",
    strIngredient1: "Vodka",
    strIngredient2: "Grenadine",
    strIngredient3: "Orange juice",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "1 tblsp ",
    strMeasure3: "Fill with ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-04-24 22:14:53",
  },
  {
    idDrink: "17229",
    strDrink: "Adios Amigos Cocktail",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Martini Glass",
    strInstructions:
      "Shake together all the ingredients and strain into a cold glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten vermengen und in ein kaltes Glas abseihen.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/8nk2mp1504819893.jpg",
    strIngredient1: "Rum",
    strIngredient2: "Dry Vermouth",
    strIngredient3: "Cognac",
    strIngredient4: "Gin",
    strIngredient5: "Fresh Lime Juice",
    strIngredient6: "Sugar Syrup",
    strIngredient7: "Water",
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "1/2 shot ",
    strMeasure3: "1/2 shot ",
    strMeasure4: "1/2 shot ",
    strMeasure5: "1/4 shot",
    strMeasure6: "1/4 shot",
    strMeasure7: "1/2 shot ",
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-07 22:31:33",
  },
  {
    idDrink: "12560",
    strDrink: "Afterglow",
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball Glass",
    strInstructions: "Mix. Serve over ice.",
    strInstructionsES: null,
    strInstructionsDE: "Mischen. Auf Eis servieren.",
    strInstructionsFR: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vuquyv1468876052.jpg",
    strIngredient1: "Grenadine",
    strIngredient2: "Orange juice",
    strIngredient3: "Pineapple juice",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 part ",
    strMeasure2: "4 parts ",
    strMeasure3: "4 parts ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-07-18 22:07:32",
  },
  {
    strDrink: "Alice Cocktail",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/qyqtpv1468876144.jpg",
    idDrink: "12562",
  },
  {
    strDrink: "Amaretto fizz",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/92h3jz1582474310.jpg",
    idDrink: "178321",
  },
  {
    strDrink: "Aperol Spritz",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/iloasq1587661955.jpg",
    idDrink: "178325",
  },
  {
    strDrink: "Apple Karate",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/syusvw1468876634.jpg",
    idDrink: "12564",
  },
  {
    strDrink: "Applejack",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/sutyqp1479209062.jpg",
    idDrink: "16311",
  },
  {
    strDrink: "Aquamarine",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg",
    idDrink: "178319",
  },
  {
    strDrink: "Arizona Stingers",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/y7w0721493068255.jpg",
    idDrink: "14584",
  },
  {
    strDrink: "Arizona Twister",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ido1j01493068134.jpg",
    idDrink: "17074",
  },
  {
    strDrink: "Army special",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/55muhh1493068062.jpg",
    idDrink: "17066",
  },
  {
    strDrink: "Aviation",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ruutxt1478253328.jpg",
    idDrink: "17180",
  },
  {
    strDrink: "Bahama Mama",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/tyb4a41515793339.jpg",
    idDrink: "17267",
  },
  {
    strDrink: "Banana Cream Pi",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/m5p67n1582474609.jpg",
    idDrink: "178320",
  },
  {
    strDrink: "Bee's Knees",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/tx8ne41582475326.jpg",
    idDrink: "178317",
  },
  {
    strDrink: "Bijou",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg",
    idDrink: "17254",
  },
  {
    strDrink: "Blue Hurricane",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/nwx02s1515795822.jpg",
    idDrink: "17268",
  },
  {
    strDrink: "Bombay Cassis",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/h1e0e51510136907.jpg",
    idDrink: "17242",
  },
  {
    strDrink: "Bora Bora",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/xwuqvw1473201811.jpg",
    idDrink: "12572",
  },
  {
    strDrink: "Boulevardier",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/km84qi1513705868.jpg",
    idDrink: "17251",
  },
  {
    strDrink: "Brigadier",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/nl89tf1518947401.jpg",
    idDrink: "17825",
  },
  {
    strDrink: "Broadside",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/l2o6xu1582476870.jpg",
    idDrink: "178311",
  },
  {
    strDrink: "Brooklyn",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ojsezf1582477277.jpg",
    idDrink: "178310",
  },
  {
    strDrink: "Cherry Electric Lemonade",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/tquyyt1451299548.jpg",
    idDrink: "17174",
  },
  {
    strDrink: "Corn n Oil",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/pk6dwi1592767243.jpg",
    idDrink: "17830",
  },
  {
    strDrink: "Corpse Reviver #2",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/gifgao1513704334.jpg",
    idDrink: "17250",
  },
  {
    strDrink: "Cosmopolitan",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg",
    idDrink: "17196",
  },
  {
    strDrink: "Cosmopolitan Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/upxxpq1439907580.jpg",
    idDrink: "14133",
  },
  {
    strDrink: "Cream Soda",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yqstxr1479209367.jpg",
    idDrink: "14608",
  },
  {
    strDrink: "Dark Caipirinha",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/uwstrx1472406058.jpg",
    idDrink: "17177",
  },
  {
    strDrink: "Dirty Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vcyvpq1485083300.jpg",
    idDrink: "17181",
  },
  {
    strDrink: "Dry Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg",
    idDrink: "11005",
  },
  {
    strDrink: "Duchamp's Punch",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/g51naw1485084685.jpg",
    idDrink: "17182",
  },
  {
    strDrink: "Empellón Cocina's Fat-Washed Mezcal",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/osgvxt1513595509.jpg",
    idDrink: "17246",
  },
  {
    strDrink: "Espresso Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg",
    idDrink: "17212",
  },
  {
    strDrink: "Espresso Rumtini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/acvf171561574403.jpg",
    idDrink: "178309",
  },
  {
    strDrink: "Flaming Lamborghini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yywpss1461866587.jpg",
    idDrink: "16485",
  },
  {
    strDrink: "French Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/clth721504373134.jpg",
    idDrink: "17213",
  },
  {
    strDrink: "French Negroni",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/x8lhp41513703167.jpg",
    idDrink: "17248",
  },
  {
    strDrink: "Gagliardo",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/lyloe91487602877.jpg",
    idDrink: "12758",
  },
  {
    strDrink: "Gimlet",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg",
    idDrink: "17255",
  },
  {
    strDrink: "Gin Basil Smash",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/jqh2141572807327.jpg",
    idDrink: "178314",
  },
  {
    strDrink: "Gin Rickey",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg",
    idDrink: "17230",
  },
  {
    strDrink: "Greyhound",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/g5upn41513706732.jpg",
    idDrink: "17252",
  },
  {
    strDrink: "Honey Bee",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vu8l7t1582475673.jpg",
    idDrink: "178316",
  },
  {
    strDrink: "Hunter's Moon",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/t0iugg1509556712.jpg",
    idDrink: "17239",
  },
  {
    strDrink: "Imperial Cocktail",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/bcsj2e1487603625.jpg",
    idDrink: "12706",
  },
  {
    strDrink: "Irish Curdling Cow",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yrhutv1503563730.jpg",
    idDrink: "16987",
  },
  {
    strDrink: "Jitterbug",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/wwqvrq1441245318.jpg",
    idDrink: "16178",
  },
  {
    strDrink: "Lemon Drop",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg",
    idDrink: "14366",
  },
  {
    strDrink: "Malibu Twister",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/2dwae41504885321.jpg",
    idDrink: "15224",
  },
  {
    strDrink: "Manhattan",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/hz7p4t1589575281.jpg",
    idDrink: "11008",
  },
  {
    strDrink: "Martinez 2",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/fs6kiq1513708455.jpg",
    idDrink: "17256",
  },
  {
    strDrink: "Martinez Cocktail",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/wwxwvr1439906452.jpg",
    idDrink: "11720",
  },
  {
    strDrink: "Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg",
    idDrink: "11728",
  },
  {
    strDrink: "Mary Pickford",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/f9erqb1504350557.jpg",
    idDrink: "17188",
  },
  {
    strDrink: "Miami Vice",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/qvuyqw1441208955.jpg",
    idDrink: "13936",
  },
  {
    strDrink: "Midnight Mint",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/svuvrq1441208310.jpg",
    idDrink: "14842",
  },
  {
    strDrink: "Mojito",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/3z6xdi1589574603.jpg",
    idDrink: "11000",
  },
  {
    strDrink: "Mojito #3",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vwxrsw1478251483.jpg",
    idDrink: "15841",
  },
  {
    strDrink: "Munich Mule",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/rj55pl1582476101.jpg",
    idDrink: "178315",
  },
  {
    strDrink: "New York Lemonade",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/b3n0ge1503565473.jpg",
    idDrink: "13204",
  },
  {
    strDrink: "Oatmeal Cookie",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/bsvmlg1515792693.jpg",
    idDrink: "17266",
  },
  {
    strDrink: "Old Fashioned",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg",
    idDrink: "11001",
  },
  {
    strDrink: "Old Pal",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/x03td31521761009.jpg",
    idDrink: "17827",
  },
  {
    strDrink: "Orangeade",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ytsxxw1441167732.jpg",
    idDrink: "12618",
  },
  {
    strDrink: "Paloma",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/samm5j1513706393.jpg",
    idDrink: "17253",
  },
  {
    strDrink: "Passion Fruit Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/6trfve1582473527.jpg",
    idDrink: "178323",
  },
  {
    strDrink: "Pegu Club",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/jfkemm1513703902.jpg",
    idDrink: "17249",
  },
  {
    strDrink: "Penicillin",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/hc9b1a1521853096.jpg",
    idDrink: "17829",
  },
  {
    strDrink: "Pineapple Paloma",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/pg8iw31593351601.jpg",
    idDrink: "178327",
  },
  {
    strDrink: "Pisco Sour",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/tsssur1439907622.jpg",
    idDrink: "13214",
  },
  {
    strDrink: "Rail Splitter",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/stsuqq1441207660.jpg",
    idDrink: "12630",
  },
  {
    strDrink: "Rosemary Blue",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/qwc5f91512406543.jpg",
    idDrink: "17245",
  },
  {
    strDrink: "Ruby Tuesday",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/qsyqqq1441553437.jpg",
    idDrink: "17114",
  },
  {
    strDrink: "Salted Toffee Martini",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/3s6mlr1509551211.jpg",
    idDrink: "17233",
  },
  {
    strDrink: "Shark Attack",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/uv96zr1504793256.jpg",
    idDrink: "16273",
  },
  {
    strDrink: "Spice 75",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/0108c41576797064.jpg",
    idDrink: "178322",
  },
  {
    strDrink: "Spritz Veneziano",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/51ezka1551456113.jpg",
    idDrink: "178308",
  },
  {
    strDrink: "Tequila Sunrise",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg",
    idDrink: "13621",
  },
  {
    strDrink: "The Evil Blue Thing",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ojnpz71504793059.jpg",
    idDrink: "16271",
  },
  {
    strDrink: "The Jimmy Conway",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/wbcvyo1535794478.jpg",
    idDrink: "17826",
  },
  {
    strDrink: "The Last Word",
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/91oule1513702624.jpg",
    idDrink: "17247",
  },
];
